group_name: "test_group1"
group_id: null # null - create group in local stand. Other - find existance group
template_id: 1

modules:
  - name: common-module
    dependencies: []
    description: "common module"
    
  - name: module-A
    dependencies:
      - common-module
    description: "module a"
      
  - name: module-B
    dependencies:
      - common-module
    description: "module B"
      
  - name: module-C
    dependencies:
      - common-module
      - module-B
    description: "module-C"