[project]
name = "gitlab-scripts"
version = "1.0.0"
dependencies = [
    "tomlkit",
    "requests", 
    "pyyaml",
    "python-dotenv",
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
