[project]
name = "gitlab-scripts"
version = "1.0.0"
dependencies = [
    "tomlkit",
    "requests", 
    "pyyaml",
    "python-dotenv",
]
[project.scripts]
gitlab-scripts = "gitlab_scripts.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
